### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by mmramos** [giecaruff/stoneforge#15]
Understand more and try the usage of github actions, mostly of "Python application - Create and test a Python application."
save some tutorials on this issue dialogue.

**Comment by RishiKumarRay** [comment]
I would like to go for this assign me

**Comment by mmramos** [comment]
Hi @RishiKumarRay , you have been assigned. Thanks for the initiative, and !!!congratulations!!! you are our first external contributor, Ieeeei. My name is Mário, and I really like making loops and old programming languages ​​(Fortran, C, assembly, etc…). I also like steak with fries and lemon pie (not on the same plate). Welcome to stoneforge and feel free to talk about yourself (if you want).

**Comment by RishiKumarRay** [comment]
@mmramos Thank you , I am glad , I will try my best to build github workflow for this project. I am Rishi , I am into DevOps and I like working with all the tools . Can you tell me the steps you want also , how to build and test this project locally , this will be a good help for me to setup github workflow

**Comment by mmramos** [comment]
@RishiKumarRay we are still learning to use the basics of Pytest here, and for now the idea is to check that all the functions are working, that the basic syntax of execution is correct.
A first step would be to perform the test in stoneforge/stoneforge/tests/test_water_saturation.py

later we will pass everything to pytest, and put more functions, but that's it for now. Stoneforge is at a very early stage right now.

**Comment by RishiKumarRay** [comment]
HI @mmramos I was trying to setup the pytest, getting this error while running the workflow
![Screenshot from 2022-01-29 21-40-39](https://user-images.githubusercontent.com/87641376/151668253-51773427-9735-4f90-aaa0-8f38a3eb18f1.png)

**Comment by mmramos** [comment]
Hi @RishiKumarRay  so, I don't understand much but I imagine it asked for numpy. In this case I recommend putting another line like run: pip install numpy. Another suggestion is to use the stoneforge installer: pip install stoneforge instead, as it already comes with numpy and pytest.

I see some things in this video, maybe it'll help:
https://www.youtube.com/watch?v=WTofttoD2xg

**Comment by RishiKumarRay** [comment]
@mmramos i would like to suggest you to add something like requirements.txt to maintain everything that is needed to run this project . i have seen that in many projects i have worked before . It makes easy to run application. Also thanks for the suggestions i hope it works now and i will raise a. PR soon

**Comment by mmramos** [comment]
Hi @RishiKumarRay  Ok, I'll do that this monday. Thanks for your recommendations, and for all the help provided. If you have more suggestions, feel free to speak up. I understand that from the community's point of view, there would still be a few steps left to be able to publish on PyPI, but I really needed to make the library available in this way for the other applications of our institution.

**Comment by RishiKumarRay** [comment]
@mmramos Hey , I have raised a PR as of now adding a step of installing numpy before pytest and its working fine , Thanks for your suggestions. please do review

**Comment by RishiKumarRay** [comment]
@mmramos thanks for merging this PR , also i will suggest in future when you added requirements file just replace github actions numpy installation step with installing all dependencies at once. And you're good to go ... Or if you do anything else in automation let me know, i will try to help as much as possible. Thanks
