### ISSUE TITLE
up to date with all suggestions

### ISSUE THREAD

**Issue by mmramos** [giecaruff/stoneforge#21]
by @RishiKumarRay :
- [ ] add requirements.txt "to maintain everything that is needed to run this project ."
- [ ] Do the tests using the requirements file.

by @rmotadutra / @fabiojdf :
- [x] add folder tests_water_saturation.
- [x] add folder tests_porosity.

OBS: do some tests first.

**Comment by Yuri211200** [comment]
folders added!

**Comment by DChrispim** [comment]
Fechando para reformulação dos testes.
