### ISSUE TITLE
dependencies version

### ISSUE THREAD

**Issue by mmramos** [giecaruff/stoneforge#7]
it's not better to set, for example, "numpy>=1.20.0" or "pytest>=6.2.2" instead of "numpy==1.20.0"?

My argument is that this will made stoneforge more flexible for any subsequent modification on appy-core and appy-gui.

**Comment by rmotadutra** [comment]
I'm not sure if this is the best option for the packages versions. But, for the python version I think the best option is to set `python>=3.8.8`.

**Comment by fabiojdf** [comment]
I'm not sure too. Maybe by this way a version 2.x of some package will be installed and could broke some functionalities of stoneforge. I don't know if "numpy>=1.20.0" will install only 1.x versions.

**Comment by mmramos** [comment]
Good questions, I put an attached image of the test that I made.
The installation was made in a clean enviroment only with python 3.8.8
numpy and pytest are the latest version. 

A test was made also using “...python>=3.8” and I get a crash.

![issue_python_version_1](https://user-images.githubusercontent.com/9342057/150838264-61d4d65b-c21c-4bd6-98b0-c459a15a13a1.jpg)
![issue_python_version_2](https://user-images.githubusercontent.com/9342057/150838266-c3ae7bf9-c118-44f1-9b02-0066f3c0252c.jpg)

I made an final attempt here that appears to be the best using "numpy>=1.20.0, <=1.25.0"
![issue_python_version_3](https://user-images.githubusercontent.com/9342057/150840036-da1827ee-c774-45a9-90a3-f57733f6b3ed.jpg)

I think the last one is the best way
