### ISSUE TITLE
Problems when installing version from PyPi

### ISSUE THREAD

**Issue by albano-a** [giecaruff/stoneforge#80]
(This issue serves just as an organization issue, the problem was already solved in the most recent branch, just not merged yet)
The Stoneforge version from PyPi is outdated (`v0.1.4`). When trying to do the command `pip install stoneforge`, this is the output:

![image](https://github.com/giecaruff/stoneforge/assets/110417140/b9a1c15f-0e25-40a6-91ee-84b5de56a4fc)
![image](https://github.com/giecaruff/stoneforge/assets/110417140/e88ddd42-fa16-4790-af82-0d2712336005)

If I run `pip install stoneforge --no-depedencies`, the installation process happens normally. However, something unexpected occurs when you attempt to import the module afterward:

![image](https://github.com/giecaruff/stoneforge/assets/110417140/9db971e0-7770-4cd4-b39c-7e40aaf48bc3)

**Comment by DChrispim** [comment]
Documentação do bug foi adicionada na wiki do stoneforge. Fechando a issue.
