### ISSUE TITLE
numpy tests research

### ISSUE THREAD

**Issue by mmramos** [giecaruff/stoneforge#9]
understand in numpy what the tests are and how they work.

- [ ] test__all__.py
- [ ] test_ctypeslib.py
- [x] test_matlib.py
- [x] test_numpy_version.py
- [ ] test_public_api.py
- [ ] test_reloading.py
- [ ] test_scripts.py
- [ ] test_warnings.py

**Comment by mmramos** [comment]
test_numpy_version.py:
take the version format as string value and compares it using regular expressions.

**Comment by mmramos** [comment]
[  test_matlib.py](https://github.com/numpy/numpy/blob/main/numpy/tests/test_matlib.py):
made several tests using matrices. 
best reference to our usage so far

**Comment by DChrispim** [comment]
Fechando para reformulação dos testes.
